# Generated by Django 4.2.7 on 2023-11-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lead.lead'),
        ),
    ]
