# Generated by Django 4.2.7 on 2023-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfile',
            name='content',
            field=models.FileField(default=1, upload_to='leadfiles'),
            preserve_default=False,
        ),
    ]
