# Generated by Django 4.2.7 on 2023-11-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_leadfile_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadfile',
            old_name='content',
            new_name='file',
        ),
    ]
